### ISSUE TITLE
Does not identify new filelog receiver

### ISSUE THREAD

**Issue by git-jayj** [lightstep/otel-config-validator#10]
I am trying validate collector config with [filelog](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filelogreceiver) receiver and it is giving the following error:

```
unknown receivers type "filelog" for "filelog" (valid values: [statsd zipkin otlp awsecscontainermetrics awsxray])

```

Sample configuration:

```yaml
receivers:
  filelog:
    include: [/usr/src/app/*.log]
    operators:
      - type: json_parser
        timestamp:
          parse_from: attributes.asctime
          layout: '%Y-%m-%dT%H:%M:%S'
        severity:
          parse_from: attributes.levelname
exporters:
  debug:
    verbosity: detailed
service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [debug]
```
