### ISSUE TITLE
Add support for sigv4auth extension

### ISSUE THREAD

**Issue by jfharden** [lightstep/otel-config-validator#8]
It would be good to add support for the [sigv4auth extension](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/sigv4authextension/README.md).

Currently validating a config using it results it an error message:

```
OpenTelemetry Collector Configuration file `pay-adot/config.yml` is not valid.


Error: unknown extensions type "sigv4auth" for "sigv4auth" (valid values: [zpages])
```

Here's an example config file using the extension:
```
receivers:
  prometheus:
    config:
      global:
        scrape_interval: 15s
        scrape_timeout: 10s
      scrape_configs:
      - job_name: "adot-sidecar-scrape-application"
        static_configs:
        - targets: [ "127.0.0.1:$APPLICATION_PORT" ]
        honor_labels: true
        honor_timestamps: true

processors:

exporters:
  prometheusremotewrite:
    endpoint: $PROMETHEUS_ENDPOINT_URL
    resource_to_telemetry_conversion:
        enabled: false
    auth:
      authenticator: sigv4auth
  logging:
    loglevel: info

extensions:
  sigv4auth:
    region: $AWS_REGION
    service: aps
    assume_role:
      arn: $PROMETHEUS_WRITE_ASSUME_ROLE_ARN

service:
  extensions: [sigv4auth]
  pipelines:
    metrics/application:
      receivers: [prometheus]
      exporters: [logging, prometheusremotewrite]
```
